server:
  port: 8761
#  servlet:
#    context-path: /eureka

spring:
  application:
    name: balabala Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
#  关闭server端自我保护机制,开发中使用
  server:
    enable-self-preservation: false






