server:
  port: 8761
#  servlet:
#    context-path: /eureka

spring:
  application:
    name: balabala Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false






